<x-app-layout>
    <div class="space-y-6">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-sm text-slate-400">Report</p>
                <h1 class="text-3xl font-bold text-white">{{ $report->title }}</h1>
            </div>
            <a href="{{ route('reports') }}" class="text-sm text-blue-400 hover:text-blue-300">← Back to Reports</a>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <!-- Summary -->
            <div class="bg-gray-800 rounded-lg border border-gray-700 p-6 space-y-4 lg:col-span-2">
                <div class="flex items-center gap-3">
                    <span class="px-3 py-1 rounded-lg text-sm font-semibold {{ $report->status === 'completed' ? 'bg-green-900 text-green-300' : ($report->status === 'pending' ? 'bg-yellow-900 text-yellow-300' : 'bg-slate-700 text-slate-300') }}">
                        {{ ucfirst($report->status) }}
                    </span>
                    <span class="px-3 py-1 rounded-lg text-sm bg-blue-900 text-blue-300 font-semibold">
                        {{ $report->type }}
                    </span>
                    @if($report->format)
                        <span class="px-3 py-1 rounded-lg text-sm bg-slate-700 text-slate-300">Format: {{ strtoupper($report->format) }}</span>
                    @endif
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-slate-300">
                    <div>
                        <p class="text-slate-400 text-xs">Generated</p>
                        <p class="font-semibold">{{ $report->generated_at?->format('M d, Y H:i') ?? 'Not generated yet' }}</p>
                    </div>
                    <div>
                        <p class="text-slate-400 text-xs">Created</p>
                        <p class="font-semibold">{{ $report->created_at->format('M d, Y H:i') }}</p>
                    </div>
                    <div>
                        <p class="text-slate-400 text-xs">Expires</p>
                        <p class="font-semibold">{{ $report->expires_at?->format('M d, Y H:i') ?? 'No expiry' }}</p>
                    </div>
                    <div>
                        <p class="text-slate-400 text-xs">Generated by</p>
                        <p class="font-semibold">{{ $report->generatedBy?->name ?? 'System' }}</p>
                    </div>
                    @if($report->file_size)
                    <div>
                        <p class="text-slate-400 text-xs">File size</p>
                        <p class="font-semibold">{{ number_format($report->file_size / 1024, 1) }} KB</p>
                    </div>
                    @endif
                </div>

                @if($report->filters)
                    <div class="pt-4 border-t border-gray-700">
                        <h3 class="text-lg font-semibold text-white mb-2">Filters</h3>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm text-slate-300">
                            @foreach($report->filters as $key => $value)
                                <div class="flex justify-between bg-gray-700/50 px-3 py-2 rounded border border-gray-700">
                                    <span class="text-slate-400">{{ Str::title(str_replace('_', ' ', $key)) }}</span>
                                    <span class="font-semibold">{{ is_array($value) ? implode(', ', $value) : $value }}</span>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endif
            </div>

            <!-- Actions -->
            <div class="bg-gray-800 rounded-lg border border-gray-700 p-6 space-y-4">
                <h3 class="text-lg font-semibold text-white">Actions</h3>
                @if($report->isAvailable())
                    @php
                        $downloadUrl = URL::temporarySignedRoute(
                            'reports.signed-download',
                            now()->addMinutes(60),
                            ['report' => $report->id]
                        );
                    @endphp
                    <a href="{{ $downloadUrl }}" class="w-full inline-flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4"/></svg>
                        Download
                    </a>
                @elseif($report->status === 'pending')
                    <div class="text-sm text-yellow-400">Report is being generated. Refresh this page to check progress.</div>
                @elseif($report->status === 'failed')
                    <div class="text-sm text-red-400">Report generation failed. Please try again.</div>
                @else
                    <div class="text-sm text-slate-400">No downloadable file available yet.</div>
                @endif
            </div>
        </div>
    </div>
</x-app-layout>
