name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * 1' # weekly

jobs:
  gitleaks-scan:
    name: Run gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks action
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}